### ISSUE TITLE
Problem download ohlc data for some coins on PROD server

### ISSUE THREAD

**Issue by GeorgeQuantAnalyst** [GeorgeQuantAnalyst/crypto-screener#13]
App have problem download OHLC data for some coins from Phemex exchange. 

**Example GOLDUSD**

Error in log:
```
2022-11-08 10:44:25,121] p7447 {data_download_step.py:58} ERROR - Problem with data download on coin GOLDUSD
Traceback (most recent call last):
  File "/home/trading-server-prod/App/crypto-screener/crypto-screener-1.1.0/crypto_screener/service/data_downloader.py", line 28, in download_ohlc
    return self.__download_ohlc(self.binance_client, ticker_prepared, time_frame, length)
  File "/home/trading-server-prod/App/crypto-screener/crypto-screener-1.1.0/crypto_screener/service/data_downloader.py", line 49, in __download_ohlc
    ohlc_daily_raw = exchange_client.fetch_ohlcv(ticker, timeframe=time_frame, limit=length)
  File "/home/trading-server-prod/App/crypto-screener/crypto-screener-1.1.0/venv/lib/python3.10/site-packages/ccxt/binance.py", line 2355, in fetch_ohlcv
    market = self.market(symbol)
  File "/home/trading-server-prod/App/crypto-screener/crypto-screener-1.1.0/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 2988, in market
    raise BadSymbol(self.id + ' does not have market symbol ' + symbol)
ccxt.base.errors.BadSymbol: binance does not have market symbol GOLDUSDT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/trading-server-prod/App/crypto-screener/crypto-screener-1.1.0/venv/lib/python3.10/site-packages/ccxt/base/exchange.py", line 620, in fetch
    response.raise_for_status()
  File "/home/trading-server-prod/App/crypto-screener/crypto-screener-1.1.0/venv/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.phemex.com/exchange/public/md/kline?resolution=14400&from=1665294264&to=1667900664&symbol=GOLDUSD
```

**Comment by GeorgeQuantAnalyst** [comment]
# Solution

The problem on the production server was with the time set backwards, which was an hour ahead.

Problem url with bad time:
https://api.phemex.com/exchange/public/md/kline?resolution=14400&from=1665292799&to=1667899199&symbol=GOLDUSD

Function url with right time:
https://api.phemex.com/exchange/public/md/kline?resolution=14400&from=1665290972&to=1667897372&symbol=GOLDUSD
